# Generated by Django 5.2.1 on 2025-05-31 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_enabled', models.BooleanField(default=False)),
                ('microphone_enabled', models.BooleanField(default=False)),
                ('screen_sharing_enabled', models.BooleanField(default=False)),
                ('face_detection_enabled', models.BooleanField(default=True)),
                ('audio_monitoring_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam_app.examattempt')),
            ],
        ),
        migrations.CreateModel(
            name='FaceDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faces_detected', models.IntegerField()),
                ('confidence_score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proctoring.proctoringsession')),
            ],
        ),
        migrations.CreateModel(
            name='AudioMonitoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noise_level', models.FloatField()),
                ('threshold_exceeded', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proctoring.proctoringsession')),
            ],
        ),
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('FACE_NOT_DETECTED', 'Face Not Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('TAB_SWITCH', 'Tab Switch'), ('WINDOW_BLUR', 'Window Lost Focus'), ('COPY_PASTE', 'Copy/Paste Attempt'), ('RIGHT_CLICK', 'Right Click'), ('NOISE_DETECTED', 'Excessive Noise'), ('SCREEN_SHARE_STOPPED', 'Screen Share Stopped')], max_length=30)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='proctoring.proctoringsession')),
            ],
        ),
    ]
