# Generated by Django 5.2.1 on 2025-05-31 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_alter_exam_created_by_alter_exam_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
    ]
