# Generated by Django 5.2.1 on 2025-11-13 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_alter_answer_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('ANSWER_SUBMITTED', 'Answer Submitted'), ('ANSWER_CHANGED', 'Answer Changed'), ('QUESTION_VIEWED', 'Question Viewed'), ('EXAM_STARTED', 'Exam Started'), ('EXAM_SUBMITTED', 'Exam Submitted'), ('TAB_SWITCHED', 'Tab Switched'), ('WINDOW_FOCUS_LOST', 'Window Focus Lost'), ('WINDOW_FOCUS_GAINED', 'Window Focus Gained'), ('COPY_ATTEMPTED', 'Copy Attempted'), ('PASTE_ATTEMPTED', 'Paste Attempted'), ('RIGHT_CLICK', 'Right Click Detected'), ('KEYBOARD_SHORTCUT', 'Keyboard Shortcut Used')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data about the activity')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='marks_awarded',
            field=models.FloatField(blank=True, help_text='Marks awarded for this answer', null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='time_taken_seconds',
            field=models.IntegerField(blank=True, help_text='Time taken to answer in seconds', null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='auto_calculate_total',
            field=models.BooleanField(default=True, help_text='Automatically calculate total marks from questions'),
        ),
        migrations.AddField(
            model_name='exam',
            name='enable_negative_marking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='enable_partial_marking',
            field=models.BooleanField(default=False, help_text='Enable partial marks for partially correct answers'),
        ),
        migrations.AddField(
            model_name='exam',
            name='negative_mark_percentage',
            field=models.FloatField(default=0.25, help_text='Percentage of marks to deduct for wrong answer (e.g., 0.25 = 25%)'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='evaluation_notes',
            field=models.TextField(blank=True, help_text='Admin notes about the evaluation', null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='is_passed',
            field=models.BooleanField(blank=True, help_text='Whether candidate passed based on passing marks', null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='percentage_score',
            field=models.FloatField(blank=True, help_text='Percentage score', null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='unanswered_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='score',
            field=models.FloatField(blank=True, help_text='Final score after evaluation', null=True),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'question'], name='exam_app_an_attempt_d6f978_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_correct'], name='exam_app_an_is_corr_962c84_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', 'exam'], name='exam_app_ex_user_id_e4fcfb_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status'], name='exam_app_ex_status_4f6744_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', 'status'], name='exam_app_ex_exam_id_c54d6d_idx'),
        ),
        migrations.AddField(
            model_name='examactivitylog',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='exam_app.examattempt'),
        ),
        migrations.AddIndex(
            model_name='examactivitylog',
            index=models.Index(fields=['attempt', 'timestamp'], name='exam_app_ex_attempt_bc23a4_idx'),
        ),
        migrations.AddIndex(
            model_name='examactivitylog',
            index=models.Index(fields=['activity_type', 'timestamp'], name='exam_app_ex_activit_c5ecc6_idx'),
        ),
    ]
