# Generated by Django 5.2.1 on 2025-11-13 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_examactivitylog_answer_marks_awarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_image',
            field=models.ImageField(blank=True, help_text='Image for the option', null=True, upload_to='options/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, help_text='Image for the question', null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated'), ('PAUSED', 'Paused')], default='STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('SA', 'Short Answer'), ('TEXT', 'Text Answer'), ('IMAGE_UPLOAD', 'Image Upload Answer')], default='MCQ', max_length=15),
        ),
        migrations.CreateModel(
            name='AnswerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Answer image (max 10MB)', upload_to='answers/')),
                ('order', models.IntegerField(default=0, help_text='Order of image (0-2)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_images', to='exam_app.answer')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('answer', 'order')},
            },
        ),
    ]
