# Generated by Django 5.2.1 on 2025-11-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0006_examattempt_results_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data like retake requests, tags, etc.'),
        ),
        migrations.AddField(
            model_name='question',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data like tags, difficulty, etc.'),
        ),
    ]
