# Generated by Django 5.2.1 on 2025-12-07 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0007_exam_metadata_question_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_manually_marked',
            field=models.BooleanField(default=False, help_text='Whether this answer was manually marked by admin'),
        ),
        migrations.AddField(
            model_name='answer',
            name='needs_manual_marking',
            field=models.BooleanField(default=False, help_text='Whether this question type requires manual marking'),
        ),
        migrations.AddField(
            model_name='answer',
            name='solution_text',
            field=models.TextField(blank=True, help_text='Correct solution explanation', null=True),
        ),
        migrations.CreateModel(
            name='SolutionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Solution attachment file (PDF, DOC, etc.)', upload_to='solutions/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, help_text='e.g., pdf, doc, docx, jpg, png', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_attachments', to='exam_app.answer')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Admin who uploaded this', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
