# Generated by Django 5.2.1 on 2025-12-07 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0008_answer_is_manually_marked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Answer attachment (PDF, DOC, DOCX, etc.)', upload_to='answer_attachments/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, help_text='e.g., pdf, doc, docx, txt, xlsx', max_length=50)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='exam_app.answer')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
